### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/ts-express-decorators#1436]
Are there any benchmarks available for tsed 6?

For instance, it'd be great to see how it compares to plain Express, Fastify, Hapi, etc.
I imagine it'd be slower since it adds more logic and abstraction on top of these, but I'm curious to see to what extent.

**Comment by Romakita** [comment]
Hello @royibernthal 
The benchmark is run for each job on the CI (look benchmark). But the result isn't stable / pertinent / consolidated, This is why I take a time to learn/investigate and create a correct benchmarks.
I know there is small performance issue on a simple helloworld (this is the tested scenario). It doesn't reflect the reality. 

I have a task to improve perf  and understand where the problem is. 

For example Ts.ED use Express.Router, maybe it's the first point I have to improve.  
I also identified a perf issue on the createContextMiddleware, this point is pretty obscure for me. See the this code:

https://github.com/tsedio/tsed/blob/production/packages/common/src/platform/utils/createContext.ts#L16

Instantiate Context take a long time.

So I try work on it, but I find it hard to understand why some part of the code is not necessarily efficient. Any help is welcome.
See you
Romain

**Comment by royibernthal** [comment]
Hey @Romakita 

Thanks for the detailed response.

I understand the situation, wish I had time to help with that.

I wanted to go with this framework for a big new project my company is working on because I personally really like it (hence my interest in benchmarks), but we ended up going the simplistic & unopinionated way.

Regards,
Royi
