### ISSUE TITLE
Support schema based multi-tenancy for postgres with TypeORM

### ISSUE THREAD

**Issue by kryptus36** [TypedProject/ts-express-decorators#1443]
**Is your feature request related to a problem? Please describe.**

I'm trying to design a multi-tenancy app that requires per-request schema switches.

**Describe the solution you'd like**
I'm ultimately trying to accomplish exactly what is described here:
https://tech.canyonlegal.com/multitenancy-with-nestjs-typeorm-postgres

I don't know exactly what the implementation would ultimately look like. Maybe @UseSchema(schemaName)?

**Describe alternatives you've considered**
I could just use NestJS and do exactly as above, but I find tsed more approachable.

**Comment by Romakita** [comment]
Hello @kryptus36 
I don't understand the needs. Create new decorator for multi tenant application has no sense. For example, the swagger documentation expose statics schema for all endpoint, so describe dynamic schema isn't possible. If an endpoint expose a different response structure per tenant, you won't be able to describe it excepted for common props.

The given nestjs example doesn't help me to understand the necessity to implement a new decorator...

By using middleware to handle the multi tenant, create connection is it's necessary in the middleware, expose generic controllers (because the main idea of multi tenant is to expose the same controllers/models/business and doesn't develop custom things for one tenant, as far as possible) and get data from TypeORM repository.

By using `@tsed/async-hook-context` it'll simplify the process to forward tenantId through the middleware to the repository.

```typescript
@Middleware()
export class TenantMiddleware {
  @Inject()
  typeORMService: TypeORMService;
   
  use(@Context() $ctx: Context) {
     const tenantId = this.getTenantId($ctx);
    
    if (tenantId) {
      const connectionName = `tenant_${tenantId}`;

      // create connection if not exists
      await this.typeORMService.createConnection(connectionName);

      $ctx.set('tenantId', tenantId);
    }
  }

  getTenantId($ctx: Context) {
     const [hostTenantId] = $ctx.request.host().split('.')
     if (hostTenantId !== 'mydomain') { // change the domain
        return tenantId;
     }
   
     if ($ctx.request.url().startsWith('/tenants')) {
        return $ctx.request.url().split('/')[0]
     }
    
     return $ctx.request.get('tenant-id') // by header
  }
}
```

Then use the tenantId in the service:

```typescript
@Injectable()
export class GameService {
   @InjectContext()
   $ctx: Context; // require @tsed/async-hook-context
   
   @Inject()
   typeORMService: TypeORMService;

   get repository() {
     return this.typeORMService.get(this.$ctx.get('tenantId')).getRepository(GameEntity)
   }

  async findAllByTeamId(teamId): Promise<GameEntity[]> {
    return await this.repository.find({ where: { teamId }});
  }
}
```
That all :)

My point is, there is no need to develop something specific to manage multi tenant application.

See you
Romain

**Comment by kryptus36** [comment]
Thank you! I'll try this and re-open if I can't get it to work.
