### ISSUE TITLE
Disable logger on certain routes?

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/ts-express-decorators#1572]
For example, in login and register POST requests, you can see a user password as part of the POST body in the raw string format. It would be nice if there was a way to customize the logger functionality on a per-route basis.

Thanks for the great framework!

**Comment by Romakita** [comment]
Hello @reed-lawrence 
Hum... Have you changed the logger configuration. Because by default, the logger doesn't display the body payload in the log:

https://github.com/tsedio/tsed/blob/production/packages/di/src/domain/ContextLogger.ts#L55
and 
https://github.com/tsedio/tsed/blob/production/packages/platform/platform-log-middleware/src/middlewares/PlatformLogMiddleware.ts#L14

The default configuration will display the following: ["reqId", "method", "url", "duration"]

In debug, error, warn, trace level, the body is displayed but it's intended!

So you have the followings solutions:
 - exclude some route from logs
 - Override the PlatformLogMiddleware and update the implementation to be aligned with your need :)
 - Make a PR ^^

Customize logger peer route will be complicated, it'll be better to find a generic rules to remove or obfuscate the fields when the logger serialize the object. 

See you
Romain
