### ISSUE TITLE
Thanks and one question regarding using https

### ISSUE THREAD

**Issue by daobuihuu-nhs** [TypedProject/ts-express-decorators#1596]
Firstly, thanks for building a great library.

I'm currently exploring it to use for my new project and found it's very useful with decorators and supported plugins.
As I'm quite new to nodejs and express and frontend stack, those made me feel at home coming from backend background.

I have one question building application using https. I can't find any example related to it and not sure how to wire up https with the library using express.

It may be a noob question but I just started learning nodejs lately so appreciate that you can help to answer this.

Thanks

**Comment by Romakita** [comment]
Hello @daobuihuu-nhs 

The https example isn't  provided because in local you don't need it and now, the https is managed by your cloud provider and you just need to expose your nodejs app as http.

For example, heroku managed itself the SSL certificat. And I just need to expose the server in http.

For your question. You need to generate a self signed certificat. You can find many tutorial on google ;)

Then you have to provide the certificat to the httpsOptions. I'll try to give you an example ;)

See you
Romain

**Comment by daobuihuu-nhs** [comment]
Hi Romakita,

Thanks for prompt reply. Turned out `httpsOptions` is what I looking for :).
I missed it when scrolling through the documentation

I managed to solve it by supplying the key and cert as below

```typescript
@Configuration({
  rootDir,
  acceptMimes: ['application/json'],
  port: process.env.PORT,
  httpsPort: '8082',
  httpsOptions: {
    key:  fs.readFileSync('certs/key.pem'),
    cert: fs.readFileSync('certs/certificate.pem')
  },
  mount: {
    '/api': [`${rootDir}/controllers/**/*.ts`],
  },
  componentsScan: [`${rootDir}/middlewares/**/**.ts`],
})
```
