### ISSUE TITLE
[Feature Request] Generate multiple things at once

### ISSUE THREAD

**Issue by p32929** [TypedProject/ts-express-decorators#1744]
First of all, I wanna thank you guys for creating and maintaining tsed. 

When we try to generate something using `tsed g`, it only allows us to generate one thing at a time.
![Screenshot (151)](https://user-images.githubusercontent.com/6418354/151536413-e1220fb2-7590-4bba-a4ad-f6f1102c0297.png)

it would've been even more awesome, if we could generate multiple things at once like the screenshot below using the `tsed g` command:
![Screenshot (152)](https://user-images.githubusercontent.com/6418354/151536599-9785f602-a1e1-4eac-b431-31b3d930e47a.png)

Thanks a million

## Acceptance criteria

- [ ] Being able to generate multiple providers using `tsed g` or may be another command like `tsed extended-generate` or `tsed eg`

**Comment by Romakita** [comment]
Hello @p32929 
Thanks for this issue :)

The idea is not bad, but complicated, because each selected value will be followed by a prompts to fill the name and additional options. The solutions could be the following:

The code is here:
https://github.com/tsedio/tsed-cli/blob/master/packages/cli/src/commands/generate/GenerateCmd.ts#L95

We have to prompt in first the features lists 
```typescript
const selectedProviders = await Inquirer.prompt({
        type: "autocomplete",
        name: "type",
        message: "Which type of provider ?",
        default: initialOptions.type,
        when: () => proposedProviders.length > 1,
        source: searchFactory(proposedProviders)
})
```
> Add the options to select multiple items. See inquirer-autocomplete options for that.

Then generate for each selected item the others prompts options and store response in ctx.items instead of ctx GenerateCmdContext) itself.

So we need to update the GenerateCmdContext:

**before**
```typescript
export interface GenerateCmdContext extends CliDefaultOptions {
  type: string;
  name: string;
  route: string;
  platform: string;
  templateType: string;
  symbolName: string;
  symbolPath: string;
  symbolPathBasename: string;
  convention: ProjectConvention;
}
```

**after**
```typescript
export interface GenerateItemOpts {
   type: string;
  name: string;
  route: string;
  platform: string;
  templateType: string;
  symbolName: string;
  symbolPath: string;
  symbolPathBasename: string;
}

export interface GenerateCmdContext extends CliDefaultOptions {
  items: GenerateItemOpts[];
  convention: ProjectConvention;
}
```

Finally, we have to update the `mapContext` and `$exec` to handle the new interface and generate each items.

See you
Romain

**Comment by p32929** [comment]
Thanks for the amazing explanation. I'll give it a try and send a pull request.

**Comment by p32929** [comment]
BTW, is it okay, if instead of implementing myself, if I just send you this as a feature request? Thanks in advance...
( yes, I tried to do the things you explained and got some errors. So, I thought, it would be better to leave it up to the maintainers )
