### ISSUE TITLE
[BUG] Title  cant use BodyParams decorator in controller

### ISSUE THREAD

**Issue by pryme0** [TypedProject/ts-express-decorators#1752]
## Information

- **Version:** 5.x
- Packages: 

A few sentences describing the overall goals of the issue.
I am trying to get request  body  from a post controller using the @BodyParams decorator but every time i try to run my sever i get the error response below

`TypeError: Cannot read properties of undefined (reading 'paramType')`

## Example
here is a copy of my controller route
`  @Post('/v1/graphql')
  async handleProxy(
    @Context() ctx: Context,
    log: Log,
    @BodyParams('query') query: string
  ) {
    const proxy = await handleProxy(ctx.request.raw, log);
    return proxy;
  }`

i am runnig tsed version 3.17.0

 Any help with this will be really appreciated thanks

**Comment by Romakita** [comment]
Hello @pryme0 

- please format correctly your issue (use three back tick, postfixed by typescript to colorize code)
- Are you sure your running the code on Ts.ED v3.17.0. Because your example is not for v3. And I won’t give answer for this version, which is totally unmaintened/obsolete.
- I don’t undersrand your issue, you’ve forgot the context. Why you have a /v1/graphql what is the goal of this route. For there is no issue with bodyparams. 
- have you the same versions for all Ts.ED packages (excepted logger) ?

see you
