### ISSUE TITLE
[BUG] Passport oauth2

### ISSUE THREAD

**Issue by gdraganic** [TypedProject/ts-express-decorators#1864]
## Information

- **Version:** 6.x
- Packages: @tsed/passport

It is not possible to extract additional OAuth2 information with the `$onVerify` function. When using standalone passport it is achieved with the following verify callback:

> function (req, accessToken, refreshToken, **params**, profile, done) {

The cause of the problem is here:
https://github.com/tsedio/tsed/blob/edc607caa18626d1bd2890c5200d2e3dabbd31af/packages/security/passport/src/services/ProtocolsService.ts#L137-L157

because `passport-oauth2` module expects verify function to have either 5 or 6 arguments (but in runtime and passport init it only thinks there is 1 arg):

https://github.com/jaredhanson/passport-oauth2/blob/ee3fe9f17c0f3a90f2d9d938f267e9942b9fba49/lib/strategy.js#L193-L199

**Comment by Romakita** [comment]
Hello @gdraganic 

As it's explain in the documtentation: https://tsed.io/tutorials/passport.html#discord-auth, you can use the `@Arg` or `@Args` decorator for that:

```typescript
  async $onVerify(@Context() $ctx: Context, @Arg(0) accessToken: string) {
    const profile = await this.client.getUserInfo(accessToken);

    this.setCookies(accessToken, profile, $ctx);

    return profile;
  }
```

See you
Romain

**Comment by gdraganic** [comment]
Hi @Romakita,

There is no problem in retrieving `accessToken`, `refreshToken` and `profile`, it works well with both `@Arg` and `@Args` decorators. 

However it is not possible to extract the `params` field (which contains properties like `expires_in` , `scope` and `token_type`): https://github.com/jaredhanson/passport-oauth2/issues/82#issuecomment-305136510

It is not possible because of the reasons explained in the initial issue description.

**Comment by Romakita** [comment]
Ok I see, the oauth passport module test if the signature have the expected number of argument. I'm sorry but I can't fix it. The problem is about the passport-oauth which uses a bad way of injecting the parameters and not my way of implementing a code which must work with the set of strategies provided by passport (each passport have is own verify signature). I won't implement a specific use case for that.

This code is really dirty and explain why some library is a nightmare for me:

```javascript
  if (self._passReqToCallback) {
  var arity = self._verify.length;
  if (arity == 6) {
    self._verify(req, accessToken, refreshToken, params, profile, verified);
  } else { // arity == 5
    self._verify(req, accessToken, refreshToken, profile, verified);
  }
} else {
  var arity = self._verify.length;
  if (arity == 5) {
    self._verify(accessToken, refreshToken, params, profile, verified);
  } else { // arity == 4
    self._verify(accessToken, refreshToken, profile, verified);
  }
}
```
For me, it's not a bug! Ask the oauth passport author to provide a way to force the params consumption (not based on the  function args number). I'm not here to fix all bad implementation ^^. And I don't understand why It maintain two signatures...

And retrieve expires and scopes isn't complicated. You just need to decrypt the jwt token:

```typescript
const base64url = require("base64url");

export function decodeToken(token: string) {
  return JSON.parse(base64url.decode(token.split(".")[1]));
}

const decodedToken = decodeToken(accessToken);
```
See you
Romain
