### ISSUE TITLE
What is @Module() and how to use them?

### ISSUE THREAD

**Issue by bloodred17** [TypedProject/ts-express-decorators#1917]
## Information

**Is your feature request related to a problem? Please describe.**
While using `tsed generate` I noticed Modules, I want to know if it works similar to how a Module works in NestJs?  If so, how? I couldn't find any documentation for it in the tsed.io.

I wanted to make a Module implementation of an API. While importing it in my module I want to provide the API key. And I want to import this module at different places with different api keys and not reinitialize it again and again.

This is how I do it in NestJs. 
```ts
@Module({
  imports: [
    ImageStorageModule.register({
      cloudinaryConfig: {
        cloudName: 'dasdfask',
        apiKey: '1905232423424345235345539390963176',
        apiSecret: 'NZaPa3490daf0mFAdfweir9EasmChretert72TBbMvcbxccQmzr23fasf'
      }
    }),
  ]
})
export class SeaTrackingModule {
}

@Module({
  imports: [
    ImageStorageModule.register({
      cloudinaryConfig: {
        cloudName: '34asdfask',
        apiKey: '445230809053945345343248678343176',
        apiSecret: '3dsfasf3490daf0mFAdfweir9EasmChretert72TBbMvcbxccQmzr23fasf'
      }
    }),
  ]
})
export class AirTrackingModule {
}
```
Is it possible in TsED? If so how?

**Describe the solution you'd like**
I would like a documentation on how to use Modules and related examples.

**Describe alternatives you've considered**
Currently using services to do it, using a regular member call.

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @bloodred17 ,

The `@Module` is not really similar to Nestjs (or partially). By definition, a module in nodejs is a file. Ts.ED use this philosophy to consider all imported files through an ES import as a module.

The module decorator is just here to organize the code and implements hooks to intercept some Ts.ED events. Module and Injectable are similar!

https://github.com/tsedio/tsed/blob/production/packages/orm/mongoose/src/MongooseModule.ts

I'm personally not in favor of the design adopted by Nest and Angular concerning the decorator Module. I have the impression that it is a big overlay to the Native ESM module.

In this case, I prefer to use configurable provider: https://tsed.io/docs/providers.html#configurable-provider

Actually, the `@Module` isn't documented because, his usage was for an internal purpose but it can be used to organize your code ;)

See you
Romain :)
