### ISSUE TITLE
[BUG] Error: Cannot find module './Socket'

### ISSUE THREAD

**Issue by moskoweb** [TypedProject/ts-express-decorators#2173]
## Information
After the last update, the application simply no longer boots.

## Example

```ts
[2022-11-22T17:43:40.030] [DEBUG] [TSED] - Start server...
Error: Cannot find module './Socket'
Require stack:
- /app_folder/node_modules/@adiwajshing/baileys/lib/index.js
- /app_folder/src/services/Instance.ts
- /app_folder/src/controllers/InstanceController.ts
- /app_folder/node_modules/@tsed/components-scan/lib/index.js
- /app_folder/node_modules/@tsed/common/lib/index.js
- /app_folder/src/index.ts
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
	at Function.Module._resolveFilename (/app_folder/node_modules/tsconfig-paths/src/register.ts:90:36)
	at Function.Module._load (node:internal/modules/cjs/loader:841:27)
	at Module.require (node:internal/modules/cjs/loader:1061:19)
	at require (node:internal/modules/cjs/helpers:103:18)
	at Object.<anonymous> (/app_folder/node_modules/@adiwajshing/baileys/lib/index.js:20:34)
	at Module._compile (node:internal/modules/cjs/loader:1159:14)
	at Module._compile (/app_folder/node_modules/source-map-support/source-map-support.js:568:25)
	at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
	at Object.nodeDevHook [as .js] (/app_folder/node_modules/ts-node-dev/lib/hook.js:63:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
	'/app_folder/node_modules/@adiwajshing/baileys/lib/index.js',
	'/app_folder/src/services/Instance.ts',
	'/app_folder/src/controllers/InstanceController.ts',
	'/app_folder/node_modules/@tsed/components-scan/lib/index.js',
	'/app_folder/node_modules/@tsed/common/lib/index.js',
	'/app_folder/src/index.ts'
  ]
}

```

## Package
```
"@tsed/ajv": "7.0.0-alpha.2",
    "@tsed/common": "7.0.0-alpha.2",
    "@tsed/core": "7.0.0-alpha.2",
    "@tsed/di": "7.0.0-alpha.2",
    "@tsed/exceptions": "7.0.0-alpha.2",
    "@tsed/json-mapper": "7.0.0-alpha.2",
    "@tsed/platform-express": "7.0.0-alpha.2",
    "@tsed/platform-middlewares": "7.0.0-alpha.2",
    "@tsed/platform-views": "7.0.0-alpha.2",
    "@tsed/schema": "7.0.0-alpha.2",
    "@tsed/swagger": "7.0.0-alpha.2",
```

**Comment by Romakita** [comment]
Install latest v7 please. Alpha is outdated and any support will be provided for alpha usage.

Please check the migration guide for v6 to v7.
Note: The componentScan is deprecated ;).

see you

**Comment by Romakita** [comment]
I let you reopen this ticket when your problem is confirmed on v7.4+

**Comment by moskoweb** [comment]
I tried to update, but it no longer recognizes my routes and controllers.

**Comment by Romakita** [comment]
@moskoweb the alpha-2 wasn’t a stable version so why did you use it!!
Again Please read migration guide from v6 to v7. https://tsed.io/getting-started/migration-from-v6.html

Also generate a new project using cli and compate your code with your project. Your issue is specific to your project.

if you want a specific support please contact me on slack and I’ll propose you a commercial support. 
Opensource doesn’t means free support!

**Comment by Romakita** [comment]
Note: v7 works fine and is used in many production app. This is why I’m sure that is not a problem from the framework.

**Comment by moskoweb** [comment]
I'm not asking for support, I wanted to understand why last week it worked, and now the same project stopped working, I changed computers, and was migrating the project, I installed the packages and stopped working, that's what I didn't understand, no change at all, just reinstall, and it didn't work anymore.

I'll see if I can migrate to v7.

**Comment by Romakita** [comment]
I don’t know… you have open this issue with an incorrect package.json configuration.

My answer is simple, no support or answer will be given for that. 

my advice: rollback all change and restart the project. But if you have a problem because your app is on v7 alpha-2, I’m really sorry but I won’t be able to help you. 

Alpha, beta aren’t here to nothing… it’s to tells developpers to not use this package for a production app or any personal projects. 

You don't want support but you open an issue hoping for an answer. So you want support ;)

Unfortunately, haven’t a response for your very specific issue! Maybe your package lock have changed maybe you haven’t the same os, so dependencies are not exactly the same, maybe… maybe not! Maybe your Os is sensitive case and your Socket.ts is maybe named socket.ts.

See you
