### ISSUE TITLE
[BUG] `pnpm build` failed when tsconfig ` "declaration": true`

### ISSUE THREAD

**Issue by jukrb0x** [TypedProject/ts-express-decorators#2190]
## Information

- **Version:** 7.8.2
- Packages: 
related:
```
        "@tsed/ajv": "7.8.2",
        "@tsed/cli-core": "4.2.4",
        "@tsed/common": "7.8.2",
        "@tsed/core": "7.8.2",
        "@tsed/di": "7.8.2",
        "@tsed/engines": "7.8.2",
        "@tsed/exceptions": "7.8.2",
        "@tsed/json-mapper": "7.8.2",
        "@tsed/logger": "^6.3.3",
        "@tsed/logger-file": "^6.3.3",
        "@tsed/passport": "7.8.2",
        "@tsed/platform-cache": "7.8.2",
        "@tsed/platform-exceptions": "7.8.2",
        "@tsed/platform-express": "7.8.2",
        "@tsed/platform-log-middleware": "7.8.2",
        "@tsed/platform-middlewares": "7.8.2",
        "@tsed/platform-params": "7.8.2",
        "@tsed/platform-response-filter": "7.8.2",
        "@tsed/platform-views": "7.8.2",
        "@tsed/prisma": "7.8.2",
        "@tsed/schema": "7.8.2",
        "@tsed/swagger": "7.8.2",
```

Some files (controllers) cannot be built since the typescript declaration `*.d.ts`. when using `pnpm` to build

pnpm version: 7.18.0

I've tested yarn `1.22.19`, it's ok to `yarn build` but it failed when `pnpm build`, the error was thrown:
```
src/controllers/pages/IndexController.ts:16:5 - error TS2742: The inferred type of 'get' cannot be named without a reference to '.pnpm/@tsed+openspec@7.8.2/node_modules/@tsed/openspec'. This is likely not portable. A type annotation is necessary.

16     get(@HeaderParams('x-forwarded-proto') protocol: string, @HeaderParams('host') host: string) {
       ~~~


Found 1 error in src/controllers/pages/IndexController.ts:16

 ELIFECYCLE  Command failed with exit code 1.
```

to get around this, we write `"declaration": false,` in `tsconfig.complie.json`

I am wondering if there is any way to make it built as expected with `pnpm`?

## Example
I go with the way of official template, we have a swagger controller like this

```typescript
import { Constant, Controller } from '@tsed/di';
import { HeaderParams } from '@tsed/platform-params';
import { View } from '@tsed/platform-views';
import { SwaggerSettings } from '@tsed/swagger';
import { Hidden, Get, Returns } from '@tsed/schema';

@Hidden()
@Controller('/')
export class IndexController {
    @Constant('swagger')
    private swagger: SwaggerSettings[];

    @Get('/')
    @View('swagger.ejs')
    @Returns(200, String).ContentType('text/html')
    get(@HeaderParams('x-forwarded-proto') protocol: string, @HeaderParams('host') host: string) {
        const hostUrl = `${protocol || 'http'}://${host}`;

        return {
            BASE_URL: hostUrl,
            docs: this.swagger.map((conf) => {
                return {
                    url: hostUrl + conf.path,
                    ...conf
                };
            })
        };
    }
}
```

**Comment by Romakita** [comment]
Hello @jukrb0x 

Can you add also the typescript installed by pnpm an yarn please. If typescript is differentes, it’s probably the root cause!

If not, I suggest also to test witn npm. If the problem isn’t present using yarn/npm, it means that pnpm affect the tsc compile. That it shouldn’t! 
In this case I suggest you to open an issue on pnpm repo. Maybe, the team will have some answer that I haven’t.
I don’t use pnpm, my experience with is limited. The pnpm support was added by a contributor and this is why the pnpm pkgmanager is flagged as experimental.
My point of view is to not write specific things to be compliant with each pkgmanager. I expect to have the same behavior from any pkgmanager, but I see many bug related to pnpm on many project where on npm and yarn it works ^^´ (it doesn’t encourage me to use this pkgmanager).

See you

**Comment by jukrb0x** [comment]
Hi Romakita,

I installed the packages by the `package.json` but with different pkg manager, so typescript should be the same, and I found a workaround in  https://github.com/microsoft/TypeScript/issues/47663 and https://github.com/microsoft/TypeScript/issues/42873 . 

I chose `pnpm` bcuz it's fast, and for related project is using pnpm so I don't want to break the consistency to use `yarn`, even though it has problems it shouldn't have 👎 ... For now, I think we could only address this problem by manually imports in `IndexController.ts` to make `pnpm build` works, the root cause is unclear for me and final solution may be resolved by TypeScript in the future. :)

```typescript
import {} from '@tsed/openspec'; // pnpm install --save @tsed/openspec
```

**Comment by Romakita** [comment]
Hum ok, 
the fix is to import explicitly @tsed/openspec ^^. Ok I see the potential issue, it's clearly related to the package manager. 
I'll add the package explicitly on the package.json when the cli generate the code and add the import on the framework level.

In fact, you don't need to generate the declaration file if your project is only deployed on a server (so not distributed on npm as a package).

I'll try to fix that :)

See you
Romain Lenzotti

**Comment by jukrb0x** [comment]
Thank you for these wonderful works, we can settle this issue for now  ^^
