### ISSUE TITLE
[BUG] Nested controllers no longer produce correct routes

### ISSUE THREAD

**Issue by michael-pxr** [TypedProject/ts-express-decorators#2219]
## Information

- **Version:** 7.13.0
- Packages: `@tsed/common`

I use nested controllers. In version `v6.133.1` tsed would correctly combine the paths in the `@Controller` decorator to form the full routes in the OpenAPI Specification. In version `v7.13.0`, however, the paths are no longer correctly combined.

## Example
I have the following controllers:
```ts
@Controller({
    path: '/domain/:contextID',
    children: [
        CommentController,
    ],
})
export class DomainController {}
```

```ts
@Controller({
    path: '/comments',
    children: [FlaggedCommentController],
})
export class CommentController {}
```

```ts
@Controller('')
export class FlaggedCommentController {

    @Get('/flag')
    async list() {}

    @Post('/:commentID/flag')
    async create() {}
}
```

In version `v6.133.1` this would result in the routes `/domain/{contextID}/comments/flag` and `/domain/{contextID}/comments/{commentID}/flag` for the `FlaggedCommentController`. However, in version `v7.13.0` I get the routes `/flag` and `/{commentID}/flag`.

## Acceptance criteria

When the routes `/domain/{contextID}/comments/flag` and `/domain/{contextID}/comments/{commentID}/flag` are generated for the `FlaggedCommentController`.

**Comment by Romakita** [comment]
Hello @michael-pxr 

Thanks for the issue :)
The problem is around the swagger module. but the server generate the expected routes.

<img width="1512" alt="Capture d’écran 2023-01-19 à 20 01 36" src="https://user-images.githubusercontent.com/1763311/213536091-cb2df454-fc08-4907-a239-4d4f285fe3a2.png">

But swagger ui is wrong:

<img width="1512" alt="Capture d’écran 2023-01-19 à 20 02 22" src="https://user-images.githubusercontent.com/1763311/213536230-8eef17f5-09c8-4663-8f62-41df3a03fed6.png">

I'll fix that ;)
Romain
