### ISSUE TITLE
TSED - TYPEORM , Connection Pool Stats

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/ts-express-decorators#2339]
Hi Team, 
we are using TSED 6.x and we are facing an issue with the database connectivity. we are using SQL Server with TYPEORM as the layer with the REPOSITORY pattern. ( we have some connections that are in hang state and not refreshing itself as a result of which our API is returning errors). Underlying we are using tedious library.  

However, we want to find out if there is any way in which we can retrieve CONNECTION POOL stats at any point of type like current idle connections, pool length etc. 

Is there any way in which the integration of TSED + TYPEORM provides that. we are using PROVIDER approach to wrap up our Datasource. 

Any help on this is appreciated.

**Comment by Romakita** [comment]
Hello @panbhatt 

I won't be able to help you on this point. If you use Provider approach, you have access to the typeorm connection instance and in this case, your question is a pure TypeORM topic.

I won't create a package for that, since the v0.3.0 doesn't need a package to simplify integration between Ts.ED and TypeORM (the tutorials is enough for that :)). And v6 is under maintenance, no enhancement will be planed.

See you
