### ISSUE TITLE
Use OpenAPI/Swagger to generate the Controller/Models

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2380]
## Information

**Is your feature request related to a problem? Please describe.**
Is there a plan to generate the controller from the open-api swagger file? 

**Describe the solution you'd like**
Right now, you manually create the controllers and models and annotate them. This will then generate an open-api spec. I want the reverse: I manually write the open-api and `tsed` generates the controller/resource/models

**Comment by Romakita** [comment]
Hello @ktalebian 
It's not planed and this is not the philosophy framework. You write the controller and the spec is generated. 
You can merge an existing open spec file with the spec generated by Ts.ED, but the spec won't be used to generate controller. 

Generate controller with the appropriate decorators, is a simple tasks but what happens if you add code to link the controller to a service, or customize the generated endpoints?

It's really a huge complexity that I neither want to solve nor maintain ^^.

You are free to create a CLI to do that :) And I'm be happy to follow you on this task. To give you all information to create a CLI plugin, etc.

See you
Romain
