### ISSUE TITLE
[BUG] TSC and build fails due to tsed/prisma

### ISSUE THREAD

**Issue by miroslavrut** [TypedProject/ts-express-decorators#2405]
## Information

Version 7.34.2

As soon as prisma service or prisma repository is imported/injected anywhere in the code compile process fails due to missing declaration file for autogenerated repo for schema model:

reproduction repo: https://github.com/miroslavrut/tsedissue

Steps to reproduce:
pnpm install
pnpm build

It's possible to bypass it with disabling libChecks in tsconfig but that's not optimal solution

**Comment by Romakita** [comment]
Hello @miroslavrut 

The build command works as expected using npm/yarn packages manager. It's again related to this fucking PNPM manager that generate many symlinks for each dependencies. Typescript seems to be lost because it doesn't retrieve the UserRepository. The file is at the right place:

<img width="832" alt="Capture d’écran 2023-08-20 à 11 21 56" src="https://github.com/tsedio/tsed/assets/1763311/b50b6e4b-9458-4a4a-abca-44f183ce6012">

I don't know how to fix this issue on my level. The solution is to generate files in another directory.

I pushed a repository to show you the fix: 'https://github.com/romakita/tsedissue

See you
Romain
