### ISSUE TITLE
[BUG] Undefined ctx.request.params in Exception Filter

### ISSUE THREAD

**Issue by primozstukelj** [TypedProject/ts-express-decorators#2492]
### Describe the bug

In the Exception Filter, as recommended in documentation https://tsed.io/docs/exceptions.html#exception-filter, when accessing ctx.request.params within the catch method, the parameters are not defined, even do they were defined in the controller where error was thrown. This behavior doesn't apply for query and body object in request.

### To Reproduce

1. Create a scenario where an error is thrown in a controller, and an Exception Filter is set up to catch and handle the error.
2. Within the Exception Filter's catch method, attempt to access ctx.request.params.

### Expected behavior

The ctx.request.params object in the exception filter method should be defined, as it was defined in the controller where the error was thrown.

### Code snippets

```TypeScript
Controller

@Controller("/")
export class TestController {
  @Post("/error/:errorId")
  throwError(
    @Required()
    @PathParams('errorId', String) errorId: string,
    @Context() ctx: Context,
  ) {
    console.log(ctx.request.params); // defined => {errorId: 'something'}
    throw new Error('This is error');
  }
}

Erorr Filter

@Catch(Error)
export class ErrorFilter implements ExceptionFilterMethods {
  catch(exception: Error, ctx: PlatformContext): void {
   console.log(ctx.request.params); // undefined => {} (empty object)
   ...
  }
}
```

### Repository URL example

(https://github.com/primozstukelj/tsed-bug-error_filter)

### OS

Windows

### Node version

v16.13.2

### Library version

7.41.1

**Comment by Romakita** [comment]
Hello @primozstukelj 
After investigating your issue, the problem is related to Express.js. And it seems to be normal, regarding the source code.
Params depend on the executed endpoint with his path "/error/:id", but the ErrorFilter is applied via the middleware chain and his path is "/". => params become {}

Express.js:
```js
app.post('/rest/error/:id', (req, res) => {
    console.log(req.params) // => {id: 'id'}
  throw Error('new Error')
})

app.use('/', (err, req, res, next) => {
    console.log(req.params) // => {}
})
```
See the express.js code: https://github.com/expressjs/express/blob/master/lib/router/index.js#L274

It's not possible to change that without changing the way the error is caught for the Express platform.

See you
