### ISSUE TITLE
[BUG] Multer Middleware executed before auth middleware 

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2516]
### Describe the bug

I'm currently in progress of implementing a multer file upload and just noticed that the MulterMiddleware is executed before the auth middleware.

I debugged into here:

https://github.com/tsedio/tsed/blob/63a7911eebc2f48ed56365b57bd5cc61ee5e7413/packages/platform/platform-router/src/domain/PlatformRouters.ts#L80

And you can see the auth middleware is after the multer one:

![Bildschirmfoto 2023-11-07 um 16 28 34](https://github.com/tsedio/tsed/assets/20899975/6d0af2cd-b4b0-41f9-9a4a-4d60e9ded283)

### To Reproduce

My controller is simple:

```ts
@Controller('/admin')
// My Custom Auth Decorator, calling UseAuth underneath as described in docs
@AdminAuth({ permissions: [ Read ] })
export class AdminController {
  ...

  @Put()
  @AdminAuth({ permissions: [ Write ] })
  public async add(@MultipartFile('image') image: any) { ... }

  ...  
}
```

### Expected behavior

The Auth Middleware should be executed before the Multer Middleware to not process & upload the uploaded files's if the user hasn't even the permission to do so.

It should be generally one of the first middlewares imo, so before validations and stuff, but i think that is already the case

### OS

macOS

### Node version

20.9.0

### Library version

7.43.0

**Comment by Romakita** [comment]
Arf, the problem is related to the decorator execution order. Typescript execute Param decorators before method, property and class decorators. The MultipartFile is param decorator that add the multer middleware. It explain why the Auth is pushed after the multer. The only solution is to add a priority order like it's done for the Pipe.

Yes the middleware are executed before validation/mapping because Validation/Mapping are implemented on the Pipe level. These pipes are always executed after middlewares.

**Comment by EinfachHans** [comment]
Hey @Romakita , thanks for the explanation. So is this something we can fix in the library or something i have to fix in my application by applying a priority?

<hr>

I just mentioned this also happens for my path param validator, so i have a decorator on a param like

```ts
export function ModelById() {
  return useDecorators(IdPath(), UsePipe(ModelByIdPipe));
}
```

while `IdPath()` is 

```ts
export function IdPath(expression: string = 'id') {
  return useDecorators(PathParams({ expression, useType: Number }), Id(), Required());
}
```

I would expect the multer middleware to run after this one, because i defined them in this order:

```ts
async update(@ModelById() model: Model, @MultiparFile('image) image: any) { ... }
```

**Comment by Romakita** [comment]
No you can’t fix that on app.

the second point isn’t possible. Middleware are always executed before pipe.

**Comment by EinfachHans** [comment]
Okay, not a huge problem for me, because i automatically delete uploaded files on request failure again, but would have been cool

**Comment by Romakita** [comment]
I think you've right, but changing that isn't simple because the Pipe architecture (validation, desezialize, etc...) are always called per parameters just before the class/method execution, so after all middlewares added before the endpoint method.

Actually Ts.ED do that:

- Middlewares (Multer, Auth, other middlewares)
- Pipes 
  - ExpressionPipe
  - ValidationPipe
  - DeserializePipe
  - Other Pipes
  - Endpoint
 

If we want to have a logical order execution to prevent unnecessary upload or code execution, the workflow should be
- Expression parsing  (eq: ExpressionPipe)
- Validation, (eq; ValidationPipe)
- Middlewares (Auth, multer)
- Pipes (other pipes)
- Endpoint

But this workflow doesn't work, because `@MultipartFile` depend on ExpressionPipe which depend on the multer middleware. 

So maybe Validation shouldn't be performed on Pipe but in a middleware  (the middleware should build a schema that aggregate all schemes for each parameters in one and run the validation over the request.params/headers/body/query). Changing that will be a big challenge (and maybe a breaking change).

**Comment by EinfachHans** [comment]
Imo in a logical order execution the AuthMiddleware would be even before ValidationPipe, wouldn't it? 🤔 If there is no permission to execute the function, there would be no need to validate anything.

But i understand that this isn't possible currently, thanks for the explanation! What i didn't understand completely yet is if your answer means only the Multer <> Valdiation stuff (so multer is currently executed before validation) or also the Multer <> Auth stuff (multer executed before the auth is checked).

The second is a way bigger problem imo, because a un-authorized user can cause real cost in my case, becasue every file is uploaded to s3.

**Comment by Romakita** [comment]
Yes sure. I'll try to fix that ASAP ;)

**Comment by Romakita** [comment]
Hello @EinfachHans,
How is implemented your auth decorator ? I just need to be sure that the fix will work as expected ;)

**Comment by EinfachHans** [comment]
Hello @Romakita ,

my Decorator is implemented like this:

```ts
export function AdminAuth(options?: IAdminAuthenticationOptions) {
  return useDecorators(
    UseAuth(AdminAuthenticationMiddleware, options),
    Security('AdminAuth'),
    Returns(HttpStatus.Unauthorized, ErrorSchema),
    Returns(HttpStatus.Forbidden, ErrorSchema)
  );
}
```

**Comment by Romakita** [comment]
Ok perfect.
I found a quick win to fix this issue ;)
See you

**Comment by Romakita** [comment]
PR ready:
https://github.com/tsedio/tsed/pull/2528

**Comment by NachtRitter** [comment]
> PR ready: #2528

nice!
I faced the same issues of execution order in the project.
Could you please bring this feature to v6.x as well?

**Comment by Romakita** [comment]
No Isn't the same mechanism in v6. v6 is under maintenance, no evolution are planned right now.

**Comment by Romakita** [comment]
But @NachtRitter, You can open PR to fix that. The problem is located here in v6. It's similar of the v7 issue:

https://github.com/tsedio/tsed/blob/6.x/packages/platform/common/src/services/PlatformMiddlewaresChain.ts#L44C6-L44C40

The first step is to move the multer middleware at the end of the list :)

See you
Romain

**Comment by NachtRitter** [comment]
> But @NachtRitter, You can open PR to fix that. The problem is located here in v6. It's similar of the v7 issue:
> 
> https://github.com/tsedio/tsed/blob/6.x/packages/platform/common/src/services/PlatformMiddlewaresChain.ts#L44C6-L44C40
> 
> The first step is to move the multer middleware at the end of the list :)
> 
> See you Romain

Ok, will take a look into it.
I'd like to fix one issue in express configuration via TsEd in v6.x as well but haven't time yet to do it :sweat_smile:

**Comment by Romakita** [comment]
@NachtRitter 
> I'd like to fix one issue in express configuration via TsEd in v6.x as well but haven't time yet to do it

Which ? maybe this is also the case on v7
Can you take a time to open issue for this problem? It help us to track it and create a fix for the v7 if it's always an issue ;)

See you
