### ISSUE TITLE
[BUG] async $onInit service injection is not awaited

### ISSUE THREAD

**Issue by gullerya** [TypedProject/ts-express-decorators#2530]
### Describe the bug

When injecting service with an async `$onInit` implementation, injection being done with constructor, the injected service's own `$onInit` is running without waiting for injectee's init to be completed.
Worked fine in 6.114.18, got broken when upgraded to 6.133.1.

### To Reproduce

1. Create serviceA with async $onInit
2. Create serviceB and inject serviceA via constructor
3. Create method $onInit in serviceB
4. In serviceA implement within $onInit some await for promise which is resolved by timeout and sets `this.test = 5` after timeout
5. In serviceB read `serviceA.test` and see that it is not awaited to be set

### Expected behavior

Expected serviceB to wait for full init of serviceA

### OS

macOs

### Node version

20.9.0

### Library version

v6.133.1

**Comment by Romakita** [comment]
Hello @gullerya 

I think you made a wrong assumption about the behavior of hooks like $onInit.

It is true that the behavior seemed to you to be dependent between services but that was not the case. It's just that the `$onInit` hook was probably executed serially. It was an implementation and optimization error.

Since this version, all hooks are executed in parallel  (like events nodejs are) and I won't change this implementation because:
 - it's a huge optimization to start the server
 - it avoid implicit dependencies between Service (this is really not the intended behavior) - to resolve that, use only on $onInit to manage the sequence you want to have. (you can use Module or async factory)
 - The documentation doesn't said that the $onInit hook follow the dependencies between services!!!
 - you are on v6, only security bug are eligible to be fixed.
 - v7 have the same behavior and it's normal ;)

See you
Romain

**Comment by Romakita** [comment]
Example:

```ts
@Injectable()
class ServiceA {
   initDB() {}
} 

@Injectable()
class ServiceB {
   initSomething() {
   
   }
}

@Module()
class InitModule {
  @Inject()
  serviceA: ServiceA;

  @Inject()
  serviceB: ServiceB;

  async $onInit() {
     await this.serviceA.initDB()
     await this.serviceB.initSomething()
   }
}
```

Other option: https://v6.tsed.io/docs/custom-providers.html#use-async-factory
