### ISSUE TITLE
Missing the basics

### ISSUE THREAD

**Issue by PonchoPowers** [TypedProject/ts-express-decorators#2682]
### Is your feature request related to a problem? Please describe.

Just a quick query about the way to structure projects, all your examples include config inlined with classes, and I can't see a composition root, I like what you have done but I'd prefer to wire up all my dependencies in one place, and have all my configuration in one place, and I also prefer not using decorators so that I can change DI framework if needed without having to go around and swap out decorators, I imagine this wouldn't be too hard to achieve, but see no documentation on how to go about having a project structured as such, are you able to say whether this is something that is supported and if so are there any plans to document a project structured in this way, along with some examples?

**Comment by Romakita** [comment]
Hello @BonnieSoftware 
This is not really the philosophy of this framework. Ts.ED discover automatically Provider/Service/Factory when the code is imported. This is why there is no documentation, and I don't want support that officially.

One option is to create index.ts or di.ts where you import files. But I won't really help you because, if a Service is used by a controller and the controller is imported in Server.ts using mount options, the service will be discovered automatically.

Another way is to register service/provider manually without the decorators (https://tsed.io/docs/custom-providers.html#use-value):

```ts
import {registerProvider} from "@tsed/di";
import {MyService} from "./services/MyService";
 
registerProvivder({provide: MyService, useClass: MyService});
```

Just keep in mind, I don't give you more support around this usage (but the decorator Injectable call registerProvider directly so It shouldn't be a big issue).

See you
Romain

**Comment by Romakita** [comment]
> so are there any plans to document a project structured in this way
Actually not planed because isn't the philosophy of the framework ;)

**Comment by Romakita** [comment]
>  I also prefer not using decorators so that I can change DI framework if needed without having to go around and swap out decorators

You will always need to change something in the code, because each DI have his concept and prerequisite (Inversify, Nest.js, Ts.ED DI).
