### ISSUE TITLE
[BUG] Custom Inject Decorator Issue

### ISSUE THREAD

**Issue by autumn-sun91** [TypedProject/ts-express-decorators#2710]
### Describe the bug

I am using Mikro-ORM and am trying to use it by injecting the EntityManager object through DI, but it can only be injected based on property, so I am trying to create a separate decorator (like JPA's PersistenceContext) and use it, but instead of EntityManager, MikroOrmRegistry is returned. How can I solve this?

### To Reproduce

```typescript
// adapter
@Injectable()
export class EntityPersistenceAdapter {
  constructor(
    private readonly mapper: PostMapper,
    @PersistenceContext()
    private readonly em: EntityManager
  ) {}
}
```

```typescript
// custom decorator
export const PersistenceContext = (
  contextName?: string,
): ParameterDecorator => {
  return Inject(
    MikroOrmRegistry,
    (registry: MikroOrmRegistry) => registry.get(contextName)?.em,
  ) as ParameterDecorator;
};

```

### Expected behavior

```typescript
// expect
console.log(
      'em instanceof EntityManager',
      this.em instanceof EntityManager,
    ); // true
```

```typescript

// runtime
console.log(
      'em instanceof EntityManager',
      this.em instanceof EntityManager,
    ); // false

console.log(
      'em instanceof MikroOrmRegistry',
      this.em instanceof MikroOrmRegistry,
    ); // true
```

### OS

macOS

### Node version

v20.13.1

### Library version

v7.69.4

**Comment by Romakita** [comment]
Hello @KimTaeHyung91 

Because isn't possible to hive custom resolver forv Inject decorator while it's used as constructor param decorator.
This is not a bug. And I don't want to implement that on constructor level. It will commlexify the DI.

Please just use the decorator Inject on propertuy and use $onInit hook instead the constructor to initialize your logic

Please this issue if all is fine.

See you
