### ISSUE TITLE
TypeORM Synchronization Issues

### ISSUE THREAD

**Issue by BlueFrog130** [TypedProject/ts-express-decorators#636]
## Information

- **Version:** 5.x
- **Type:** Issue/Story

## Description
This issue is reguarding the configuration of TypeORM within Ts.ED and some sync issues with the provided documentation in the [docs](https://tsed.io/tutorials/typeorm.html#installation).

The provided expample _should_ create the connection (which it does) and then sync said connection with the `entities` directory. The synchronization however does not occur and the connection setup must be awaited in the bootstrapping process for any synchronization to occur. I am not sure if this is intended behavior or just a bug, but it had my head scratching for awhile.

## Example

```
@ServerSettings({
    rootDir,
    acceptMimes: ["application/json"],
    ...
    typeorm: [
        {
            name: "MyDatabase",
            type: "sqlite",
            syncronize: true,
            database: `${rootDir}/database/MyDatabase.db`,
            entities: [ 
                `${rootDir}/entities/**/*.{ts, js}`
            ],
            migrations: [
                `${rootDir}/migrations/**/*.{ts, js}`
            ],
            subscribers: [
                `${rootDir}/subscribers/**/*.{ts, js}`
            ]
        }
    ]
})

```

**Comment by Romakita** [comment]
Hello @BlueFrog130 
I don't use TypeORM currently, so for me it's a bit confusing ^^.

I'm not sure but you have a typo :
syncronize => synchronize ?

To help you (and me) the source code is there: https://github.com/TypedProject/ts-express-decorators/blob/master/packages/typeorm/src/services/TypeORMService.ts

Maybe you'll see something is wrong in the code.

See you
Romain

**Comment by cyraid** [comment]
Doesn't BaseConnectionOptions.d.ts have "readonly synchronize?: boolean;" in it's declaration? The typescript language service should've caught that no? Setting it to 'syncronize' does set off an error in type: "sqlite" so that should've triggered some form of investigation? If that is indeed the problem.

**Comment by Romakita** [comment]
Before recent release, typescript doesn't understand the options used by ServerSettings decorators, because augmented interface accros npm module is a bit tricky. I'd just discover the solution to augment correctly an interface between different npm package. Now Typescript trigger correct error when the options given for typeorm isn't correct.
