### ISSUE TITLE
Swagger package does not support https URLs

### ISSUE THREAD

**Issue by harshkothari410** [TypedProject/ts-express-decorators#683]
## Information

- **Version:** 5.x
- **Type:** Swagger does not support https.

## Description
Swagger package does not support https URLs.

## Example

```
import {} from "@tsed/common";

```

## Acceptance criteria

- [ ] Swagger should support https port.

**Comment by harshkothari410** [comment]
@Romakita

**Comment by Romakita** [comment]
@harshkothari410 What do you mean by https support exactly?
Did you have a problem with the swagger-ui or why the route mounted by the server ?

**Comment by harshkothari410** [comment]
Yes in code base it only supports http URL not https. You cannot configure swagger-ui on https URLs. @Romakita

**Comment by Romakita** [comment]
Hello. It’s just the displayed log in the terminal but the swagger is accessible through https if you change http url by https and if you use https server settings :)

**Comment by harshkothari410** [comment]
See in code `this.configuration.getHttpPort()` so its clear that getHttpPort wont return https Port. That is why I have attached screenshot. @Romakita

**Comment by Romakita** [comment]
Ok but I don't understand you're problem on this code and your issue (isn't correctly described)

1) You want a fix to display the https link in the terminal or 2) the problem is swagger ui isn't accessible in your browser through the https ?

I can said directly, the second point ok. If you configure correctly your server, the swagger ui (and all other endpoints) will be accessible in https.
See the configuration page http://tsed.io/configuration.html#http-https-server

Here a small example:
```
@ServerSettings({
    httpPort: 8080,
    httpsPort: 8081, 
    httpsOptions: {
        key: fs.readFileSync("./ssl/key.pem"),
        cert: fs.readFileSync("./ssl/cert.pem"),
        passphrase: "tsed"
    }
})
```
With this configuration the server will be accessible in http://localhost:8080 and https://localhost:8081

So by that mean , the swaggerui will be served https://localhost:8081/api-docs/ or http://localhost:8080/api-docs/ 

Again the code you figured out doesn't mean the swagger ui isn't accessible in https.

See you
Romain
